support nightly builds

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,12 +4,7 @@
 
 set -e
 
-function get_url {
-  local version=$1
-  local uname_str=$2
-
-  local version_trim=${version%.*}
-  local uname_str="$(uname)"
+function get_arch_short {
   local arch_long=$(uname -m)
 
   case "$arch_long" in
@@ -24,21 +19,88 @@ function get_url {
       ;;
   esac
 
+  echo $arch_short
+}
+
+function get_os {
+  local uname_str="$(uname)"
+
   case $uname_str in
     "Darwin")
       local os="mac"
-      local version_postfix="mac64"
-      local extension="dmg"
       ;;
     *)
       local os="$(echo $uname_str | tr '[:upper:]' '[:lower:]')"
-      local version_postfix="$os-$arch_long"
-      local extension="tar.gz"
+      ;;
   esac
 
-  url="https://julialang-s3.julialang.org/bin/$os/$arch_short/$version_trim/julia-$version-$version_postfix.$extension"
+  echo $os
+}
 
-  echo $url
+function get_file_extension {
+
+  case "$(get_os)" in
+    "mac")
+      local extension="dmg"
+      ;;
+    *)
+      local extension="tar.gz"
+      ;;
+  esac
+
+  echo $extension
+}
+
+function get_url_from_version {
+  local version=$1
+
+  local version_trim=${version%.*}
+  local arch_long=$(uname -m)
+  local arch_short=$(get_arch_short)
+  local os=$(get_os)
+  local extension=$(get_file_extension)
+
+  case $os in
+    "mac")
+      local version_postfix="mac64"
+      ;;
+    *)
+      local version_postfix="$os-$arch_long"
+      ;;
+  esac
+
+  echo "https://julialang-s3.julialang.org/bin/$os/$arch_short/$version_trim/julia-$version-$version_postfix.$extension"
+}
+
+function get_url_from_nightly {
+  local os=$(get_os)
+  local arch_short=$(get_arch_short)
+  local extension=$(get_file_extension)
+
+  case "$(get_os)" in
+    "mac")
+      local version_postfix="mac64"
+      ;;
+    "linux")
+      case "$(uname -m)" in
+        "aarch64")
+          local version_postfix="linuxaarch64"
+          ;;
+        "i686")
+          local version_postfix="linux32"
+          ;;
+        "x86_64")
+          local version_postfix="linux64"
+          ;;
+        *)
+          echo "Error: unrecognized os or arch." >&2
+          exit 1
+          ;;
+      esac
+      ;;
+    esac
+
+  echo "https://julialangnightlies-s3.julialang.org/bin/$os/$arch_short/julia-latest-$version_postfix.$extension"
 }
 
 function download_binary_archive {
@@ -46,9 +108,16 @@ function download_binary_archive {
 
   local tmp_download_dir="$(mktemp -d -t asdf-julia.XXX)"
   local tmp_download_file="$tmp_download_dir/julia.archive"
-  local url="$(get_url $version)"
 
-  curl -L "$url" > "$tmp_download_file"
+  if [[ $version == "nightly" ]]; then
+    local url="$(get_url_from_nightly)"
+  else
+    local url="$(get_url_from_version $version)"
+  fi
+
+  echo "Downloading from:" >&2
+  echo $url >&2
+  curl -L --fail "$url" > "$tmp_download_file"
 
   echo $tmp_download_file
 }
@@ -58,15 +127,10 @@ function install_julia {
     local version=$2
     local install_path=$3
 
-    if [ "$install_type" != "version" ]; then
-      echo "Error: install type must be a version!" 1>&2
-      exit 1
-    fi
-
     tmp_download_file="$(download_binary_archive $version)"
     tmp_download_dir="$(dirname $tmp_download_file)"
 
-    if [[ "$(uname)" == "Darwin" ]]; then
+    if [ "$(uname)" == "Darwin" ]; then
       local volume_path=$(
       hdiutil mount "$tmp_download_file" `# mount the dmg`\
         | grep Volume `# find the volume row in the output`\
